# Site
name: 'Perambulations'
description: 'Perambulations is where I will capture my random musings and travel lores and casual thoughts'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: ''
url: 'nehe.dev'
disqus: 'demowebsite'
email: 'anehe@cs.stonybrook.edu'
mailchimp-list: 'https://nehe.dev'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    akshay:
      name:           Akshay
      site:           https://nehe.dev
      avatar:         assets/images/avatar1.jpg
      bio:            "Hi, I am Akshay, a backend developer with interests in OS, Distributed Systems and Cloud Computing"
      email:          anehe@cs.stonybrook.edu
      twitter:        https://www.linkedin.com/in/akshaydnehe/

# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: akshay
      avatar: assets/images/avatar1.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]